name: build-vpm
on:
    push:
        tags:['*']

jobs:
    vpm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # --- パッケージだけを zip 化する
            - name: Zip subfolder
                run: |
                    ver="${GITHUB_REF##*/}"          
                    src="Packages/com.kurotori.unity-mesh-utilities"
                    zip -r "com.kurotori.unity-mesh-utilities-$ver.zip" "$src"
            
            - name: Upload artefact
                uses: softprops/action-gh-release@v2
                with: {files: com.kurotori.unity-*.zip}
            
            # --- listing.json を生成して Pages に配置 ---
            - name: Create/Update VPM listing
                uses: vrchat-community/vpm-listing-action@v1
                with:
                    package_dir: "Packages/com.kurotori.unity-mesh-utilities"
                    output: "./index.json"
