name: Deploy Pages
on:
  workflow_run:
    workflows: [Build Repo Listing]
    types: [completed]
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # アーティファクト両方を取得
      - uses: actions/download-artifact@v4
        with: { name: listing, path: site/vpm }
    #   - uses: actions/download-artifact@v4
    #     with: { name: docs, path: site/docs }

      - uses: actions/upload-pages-artifact@v3
        with: { path: site }

      - uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}